### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by sjorsroelofs** [driftyco/ionic-native#649] opened 2016-10-06 11:49 UTC
I'm using Ionic 2 RC0 and when I try to use a Ionic-native plugin, I get the following error message in the console when running on my iPhone: 
```
Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'Co(window,t.pluginRef)[e].apply')

polyfills.js:3 Unhandled Promise rejection: Cannot read property 'apply' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'apply' of undefined
```

As far as I can see, this happens at line 109 from the ionic-native code (https://github.com/driftyco/ionic-native/blob/master/src/plugins/plugin.ts#L109):
```javascript
// TODO: Illegal invocation needs window context
return get(window, pluginObj.pluginRef)[methodName].apply(pluginInstance, args);
```

The code I use for the OneSignal plugin (called inside platform.ready):
```javascript
OneSignal.init('xxxxx', {
  googleProjectNumber: 'xxxxx',
  autoRegister: true
}).subscribe(jsonData => {
  console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
});

OneSignal.enableInAppAlertNotification(true);
```

This error also triggers for the ScreenOrientation plugin, using the code:
```javascript
ScreenOrientation.lockOrientation('portrait');
```

**Comment by danielehrhardt** [comment] 2016-10-06 12:35
Same Problem here!!

**Comment by mlynch** [comment] 2016-10-06 15:02
We're trying to narrow this down. If you wrap this in platform ready and add a setTimeout for a few ms or seconds, does it work?

**Comment by sjorsroelofs** [comment] 2016-10-06 17:10
Yep, it was already in platform ready, but after a 1 second delay it works. Will use this as a temporary solution. Thanks!

**Comment by danielehrhardt** [comment] 2016-10-07 13:11
Not working at my project. I do not get any "Notification permission" prompt,

**Comment by danielehrhardt** [comment] 2016-10-07 22:36
Here is a temp Solution:
Update the SDK to 2.0.6:
`ionic plugin update onesignal-cordova-plugin`
add this to the platform ready:
```
var notificationOpenedCallback = function(jsonData) {
    console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
  };

  window["plugins"].OneSignal
    .startInit("appid", "gcmid")
  	.handleNotificationOpened(notificationOpenedCallback)
    .endInit();
  });
```

**Comment by sjorsroelofs** [comment] 2016-10-08 13:37
With that code I get the following error message:
```
2016-10-08 15:36:24.776 xxxxx[585:204144] -[NSNull intValue]: unrecognized selector sent to instance 0x19eb0b490
2016-10-08 15:36:24.777 xxxxx[585:204144] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull intValue]: unrecognized selector sent to instance 0x19eb0b490
```

**Comment by mlynch** [comment] 2016-10-08 15:11
I am guessing this is a duplicate of #602

**Comment by sjorsroelofs** [comment] 2016-10-12 06:15
@mlynch thanks, your answer fixed it: https://github.com/driftyco/ionic-native/issues/602#issuecomment-252804942

I'm now using the OneSignal code provided by @danielehrhardt without a timeout. The original OneSignal code provided by the Ionic docs still doesn't work.

**Comment by ihadeed** [comment] 2016-10-12 06:28
FYI, The OneSignal wrapper was updated in ionic-native@2.2.0 to match the
plugins latest API (v2).

**Comment by sjorsroelofs** [comment] 2016-10-12 09:12
@ihadeed I updated ionic-native to 2.2.0 and used the new code form the Ionic docs, but it gives an error (also tested it with a timeout):
``` 
2016-10-12 11:10:21.546591 xxxxx[993:232595] DEVICE READY FIRED AFTER 1388 ms
2016-10-12 11:10:21.550768 xxxxx[993:232595] ERROR: Unhandled Promise rejection: OneSignal.enableInAppAlertNotification is not a function. (In 'OneSignal.enableInAppAlertNotification(true)', 'OneSignal.enableInAppAlertNotification' is undefined) ; Zone: angular ; Task: Promise.then ; Value: TypeError: OneSignal.enableInAppAlertNotification is not a function. (In 'OneSignal.enableInAppAlertNotification(true)', 'OneSignal.enableInAppAlertNotification' is undefined) file:///var/containers/Bundle/Application/27449554-6EBE-4B21-80B5-787838A9CE27/xxxxx.app/www/build/main.js:84315:51

```

**Comment by ramonornela** [comment] 2016-10-12 09:29
@sjorsroelofs replace called method to ```enableNotificationsWhenActive``` changes in api version 2 fix usage in https://github.com/driftyco/ionic-native/pull/684/commits/8cb11e0a5147b52f166685e3aeaf461e9e44ab44

Thanks

**Comment by sjorsroelofs** [comment] 2016-10-12 09:35
@ramonornela then I get this error:
```
ERROR: Method 'enableNotificationsWhenActive:' not defined in Plugin 'OneSignalPush'
```

Also (which isn't new, a threat warning):
```
THREAD WARNING: ['OneSignalPush'] took '28.413086' ms. Plugin should use a background thread.
```

**Comment by ramonornela** [comment] 2016-10-12 09:51
@sjorsroelofs the plugin not implemented o command  [enableNotificationsWhenActive](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L130) https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/android/com/plugin/gcm/OneSignalPush.java move issue to plugin

Thanks

**Closed** 2016-10-12 11:06 UTC
