### ISSUE TITLE
Ionic 2 RC.0 - Google Analytics

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#627] opened 2016-10-03 16:53 UTC
_From @baltazaroliveira on October 3, 2016 16:37_

I finally upgraded my app to Ionic 2 RC0 and when i run the app on my Device i get a error in Google Analtycs (work on latest beta)

![image](https://cloud.githubusercontent.com/assets/953742/19045310/075cef28-8990-11e6-894e-e5345aee1924.png)

The plugin is installed

![image](https://cloud.githubusercontent.com/assets/953742/19045301/fd818432-898f-11e6-8920-013f586613fb.png)

Any have managed to work with RC.0?

Thanks
Baltazar

_Copied from original issue: driftyco/ionic#8443_

**Comment by ihadeed** [comment] 2016-10-03 17:05
@baltazaroliveira are you wrapping your call with `platform.ready().then(()=> { ... })` ? it's working fine on my rc0 app.

**Comment by mlynch** [comment] 2016-10-04 00:14
Closing as a duplicate of #602 where I show that this plugin indeed works.

**Closed by mlynch** 2016-10-04 00:14 UTC

**Comment by baltazaroliveira** [comment] 2016-10-04 07:55
Answered on post #602
