### ISSUE TITLE
NETWORK PLUGIN 

### ISSUE THREAD

**Issue by anivaisu** [driftyco/ionic-native#1037] opened 2017-02-06 07:25 UTC
Hi all,

I Update ionic-Native in my app
This is my code
import { Network} from 'ionic-native';
this.platform.ready().then(() => {
      if(Network.type === 'none')
      {
        console.log("success");
         let alert = this.alertCtrl.create({
            title: "Internet Connection",
            subTitle:"Please Check Your Network connection",
            buttons: [
                {
                    text: 'Ok',
                    handler: () => {
                        this.platform.exitApp();
                    }
                }
                ]
        });
        alert.present();
       
     }
    });
and I was installed Cordova Network plugin Information

Still I am getting this warning msg

**Native: tried calling Network.type, but the Network plugin is not installed.
pluginWarn @ plugin.js:19
plugin.js:24 Install the Network plugin: 'ionic plugin add cordova-plugin-network-information'**

again reinstall the plugin

How to fix it

Kindly advice me,
Thanks & Regards

**Comment by ihadeed** [comment] 2017-02-06 09:10
Duplicate of #1034

**Closed by ihadeed** 2017-02-06 09:10 UTC
