### ISSUE TITLE
Documentation incomplete for Google maps.

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#735] opened 2016-10-20 15:51 UTC
_From @aishacharya on October 20, 2016 6:36_

As google maps form an integral part of my application , there is not enough documentation provided in the docs for the same.(ionic-native=>Googlemaps)
A repo link as well as some detailed examples if provided would be great.
link :http://ionicframework.com/docs/v2/native/googlemap/

_Copied from original issue: driftyco/ionic#8815_

**Comment by jgw96** [comment] 2016-10-20 15:51
_From @ZiFFeL1992 on October 20, 2016 9:46_

I think you should post this here: https://github.com/driftyco/ionic-native/issues

**Comment by ihadeed** [comment] 2016-10-22 17:21
@aishacharya please use the following url http://ionicframework.com/docs/v2/native/google-maps/

We will fix the links in the docs soon.

Closing this as it's a duplicate of #734

**Closed by ihadeed** 2016-10-22 17:21 UTC
