### ISSUE TITLE
cordova-plugin-email-composer in iphone 6s isAvailable return false and then not open any email app

### ISSUE THREAD

**Issue by ominfowave** [driftyco/ionic-native#433] opened 2016-08-15 13:31 UTC
its working on android but iphone 6s is not working

**Comment by ihadeed** [comment] 2016-08-15 13:32
duplicate of https://github.com/driftyco/ionic-native/issues/432

**Closed by ihadeed** 2016-08-15 13:32 UTC

**Comment by ominfowave** [comment] 2016-08-15 13:33
ok sorry
