### ISSUE TITLE
Ionic 2 - popover doesn't come up after Camera Plugin activated to take picture or video

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-native#1019] opened 2017-01-31 15:22 UTC
_From @monalisasaha79 on January 31, 2017 3:22_

I am having a weird problem in the Ionic 2. I am sure I am missing something.
Version I am using 2.2.0

I have a popover on the home screen and FAB controller. Popover works fine till I open camera to take picture. Post closer of camera plugin my popover doesn't come up. Below my popover code is given:
```
export class AssetPage {
  	constructor(private navCtrl: NavController, private popoverCtrl: PopoverController) {}
  	
  	assetPopover(myEvent) {
	    let popover = this.popoverCtrl.create(AssetPopoverPage);
	    popover.present({
	      	ev: myEvent
	    });
	}
}
```
Camera code:
```
public captureImageFromCamera(){
    Camera.getPicture ({
      sourceType: 1,
      quality: 100,
      correctOrientation: true,
      mediaType: 0,
      encodingType: 0
    })
    .then((data) =>{
      setTimeout(() => {
        console.log (data);
        this.imageUpdate(data, 0);
      }, 0);
    }, (err) => {
      console.log ("Do nothing");
    });
  }
```
This is happening for MediaCapture plugin as well.
```
MediaCapture.captureVideo({
    }).then((localURI) =>{
      setTimeout(() => {
        this.videoUpdate(localURI[0].fullPath);
      }, 0);
    }, (err) => {
      console.log ("Do nothing");
    });
```
It is not only for the main popover. None of the popover is being displayed after camera interface activation.

Please help.

_Copied from original issue: driftyco/ionic#10250_

**Comment by monalisasaha79** [comment] 2017-02-03 00:43
Hello Ionic Team,

Need help on this issue. The problem with the popover is not only happening with Camera plugins only. Have encountered the same with keyboard plugin as well.
May be I'm missing something here.
Please help.

Thanks,
Monalisa

**Comment by ihadeed** [comment] 2017-02-03 04:22
@monalisasaha79 I'm sorry, I don't understand what the issue is here. 

Could you please create a fresh project, adding only the necessary code to demonstrate this issue? and I will gladly have a look at it.

**Comment by monalisasaha79** [comment] 2017-02-03 04:29
Hello Sir,

Issue is popover is not showing up post activation of camera / keyboard. Please find attached image.
What is happening here, popover is getting created but not overlaying the application. It might be somewhere in the background.

Please have a look at the attached image,
Thanks,
Monalisa

![image](https://cloud.githubusercontent.com/assets/25080451/22579615/8fd8d218-ea25-11e6-8755-6cf77b8cbdb4.png)

![ionic2popover-issue](https://cloud.githubusercontent.com/assets/25080451/22579604/84b43dfa-ea25-11e6-84a5-69fe1444945d.PNG)

**Comment by monalisasaha79** [comment] 2017-02-03 23:44
@ihadeed  Please find the version information below
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.3.1
Xcode version: Not installed

**Comment by ihadeed** [comment] 2017-02-04 08:29
@monalisasaha79 in your code here:
```
public captureImageFromCamera(){
    Camera.getPicture ({
      sourceType: 1,
      quality: 100,
      correctOrientation: true,
      mediaType: 0,
      encodingType: 0
    })
    .then((data) =>{
      setTimeout(() => {
        console.log (data);
        this.imageUpdate(data, 0);
      }, 0);
    }, (err) => {
      console.log ("Do nothing");
    });
  }
```

Is the promise resolving at all? is `data` defined and does it contain the expected values?

If the answer is yes to these questions, then both the plugin and `ionic-native` are functioning properly. It would be an issue with Ionic Framework or could just be a problem with your code.

It's hard to tell where the issue is with the code that you provided, I don't see a connection between the promises resolving and the popover being opened. I really recommend that you create a minimal project with only the code necessary to reproduce this issue, and then share this code on the forums to get some help with it.

**Comment by monalisasaha79** [comment] 2017-02-05 07:06
Finally as suggested by Ionic team I have recreated the project, installed all the plugins. Looks like the wired issues is gone. Popover with native plugin is working fine.
Bit sad because, I could not find the root cause. Anyway, I will keep investigating the root cause.
Thanks for your support.
Cheers!!!
Monalisa

**Comment by ihadeed** [comment] 2017-02-05 10:40
@monalisasaha79 glad you got it working!

**Closed by ihadeed** 2017-02-05 10:40 UTC
