### ISSUE TITLE
google maps setPadding not working

### ISSUE THREAD

**Issue by arielgelbard** [driftyco/ionic-native#573] opened 2016-09-23 20:28 UTC
google maps setPadding function is not working

Tried setPadding on a cordova project and it works no problem...

I am on ionic 2 beta 11

**Comment by ramonornela** [comment] 2016-09-24 22:00
Can provider more info of problem?

**Comment by arielgelbard** [comment] 2016-09-24 22:11
@ramonornela I call ```map.setPadding(0,0,200,0)``` and it executes and does not set the padding like the google sdk is suppose to do.

**Comment by ramonornela** [comment] 2016-09-25 20:10
What the version ionic-native?

**Comment by ihadeed** [comment] 2016-09-25 20:58
I doubt this is an issue with Ionic Native. It's probably just another conflict caused by Ionic Framework or could be a zoning issue. Try wrapping your `setPadding()` call with `ngZone.run()`.

**Comment by arielgelbard** [comment] 2016-09-25 21:37
@ramonornela the latest version

@ihadeed I tried `ngZone.run()` like this:
```
        this.map.on(GoogleMapsEvent.MAP_READY).subscribe((event) => {
            this.zone.run(() => {
                this.map.setPadding(0,0,200,0);
            });
        });
```
and is still not working for me...to confirm this, I tried `this.map.setClickable(false)` and it successfully executes no problem in `ngZone.run()`.

**Comment by arielgelbard** [comment] 2016-09-27 20:21
@ramonornela @ihadeed , have you tried setPadding and is working with an ionic 2 / ionic-native project?

**Comment by uditguru** [comment] 2016-09-30 15:19
Hey , I've also tried various workarounds but its noy working for me as well , please help with this if anyone can

**Comment by ramonornela** [comment] 2016-10-01 02:50
@uditguru Tomorrow I will try look at it 😉

**Comment by ramonornela** [comment] 2016-10-02 09:57
@uditguru I'm traveling many problems Internet since yesterday, I'll try later.

**Comment by ziggyJ** [comment] 2016-10-06 00:51
The issue is caused by ionic native add 2 extra null value on the args when the function is a sync call.

I have fixed it on my fork and I will provide a pull request.

**Comment by ziggyJ** [comment] 2016-10-06 01:00
My pull request here: https://github.com/driftyco/ionic-native/pull/646 
That is my simple fix, just add resolve and reject to the args if either of them is not null.
But it seems that I am touching some core functions,  I am not sure if it does not break other functions.

**Comment by ramonornela** [comment] 2016-10-06 09:14
Problem with one to three arguments in example code above has four arguments :wink:, more too exists problem mentioned 😉 

Thanks

**Comment by ramonornela** [comment] 2016-10-11 12:27
@uditguru the version 2.2.0 fix this?

**Comment by ihadeed** [comment] 2016-10-14 11:44
Closing this for now. We can re-open if you're still having issues.

**Closed by ihadeed** 2016-10-14 11:44 UTC
Labels: plugin: googlemaps
