### ISSUE TITLE
Google Maps setPadding function does not work on the android

### ISSUE THREAD

**Issue by ziggyJ** [driftyco/ionic-native#645] opened 2016-10-06 00:41 UTC
I called the setPadding(50,50,50,50), but there is no padding added on the map.

I looked into the ionic native code. The ionic native wrapper add 2 extra null value at the end of the args that makes args length to 6, but in the Google Maps Cordova plugin requires the args length is less or equal to 4.

I think adding 2 extra null value to args also breaks a lot of functions of other Cordova plugin, like Google Analytics trackView function does not work if I use ionic native.

**Comment by ihadeed** [comment] 2016-10-06 00:45
Duplicate of #573

**Closed by ihadeed** 2016-10-06 00:45 UTC
