### ISSUE TITLE
InAppBrowser insertCss should be insertCSS

### ISSUE THREAD

**Issue by aronbierbaum** [driftyco/ionic-native#938] opened 2017-01-05 21:29 UTC
It appears that https://github.com/apache/cordova-plugin-inappbrowser uses `insertCSS`. This causes an error when trying to look up the method.

```
TypeError: undefined is not an object (evaluating 'pluginObj._objectInstance[methodName].apply')
```

**Comment by spongessuck** [comment] 2017-01-06 19:29
This is probably a duplicate of #921.

**Comment by aronbierbaum** [comment] 2017-01-06 19:50
In order to workaround this I have added the following code to my project:

```typescript
const browser_proto = (this.browser as any)._objectInstance.__proto__;
browser_proto.insertCss = browser_proto.insertCSS;
```

**Comment by ihadeed** [comment] 2017-01-07 10:42
Closing in favor of #921.

**Closed by ihadeed** 2017-01-07 10:42 UTC
