### ISSUE TITLE
EXCEPTION: Uncaught (in promise): TypeError: push.on is not a function TypeError: push.on is not a function

### ISSUE THREAD

**Issue by HamzaLJ** [driftyco/ionic-native#964] opened 2017-01-11 12:57 UTC
I receive the below error:

> EXCEPTION: Uncaught (in promise): TypeError: push.on is not a function
TypeError: push.on is not a function

Knowing that my code is 100% correct, here is it:

          let push = Push.init({
               android: {
                   senderID: "34696555555",
                   vibrate:"true",
                   sound: "true"
               },
               ios: {
                   alert: "true",
                   badge: false,
                   sound: "true"
               },
               windows: {}
           });
           push.on('registration', (data) => {
               if (data) {
                    console.log('Data is valid');        
               } else {
                 console.log('No data returned.');
               }
           });`

**Comment by ihadeed** [comment] 2017-01-11 14:10
Are you waiting for `deviceready` to fire by wrapping your code with `this.platform.ready().then(() => { ... })` ?

**Comment by HamzaLJ** [comment] 2017-01-11 14:53
@ihadeed yes sure! I had the same code working on ionic 2 Beta 11, now when updating to rc4, It's showing the error.

**Comment by ihadeed** [comment] 2017-01-11 15:41
What device are you testing on? I will try to reproduce the issue.

**Comment by HamzaLJ** [comment] 2017-01-11 16:08
@ihadeed I've tested it on the browser (it was working fine on Beta 11), and also on an iOS device

**Comment by ihadeed** [comment] 2017-01-11 16:11
@HamzaLJ by browser you mean `ionic run browser` or `ionic serve` ?

**Comment by HamzaLJ** [comment] 2017-01-11 16:28
I meant `ionic serve`.
Why it shouldn't work using `ionic serve` it was working on Beta 11 ?

**Comment by ihadeed** [comment] 2017-01-11 16:31
@HamzaLJ `ionic serve` doesn't include the Cordova platforms and plugins. Therefore, when Ionic Native tries to process `Push.init` it results in a null value since the plugin scripts aren't available. 

This is the case for all plugins and not just the Push plugin. If you are trying to test out browser functionality of a plugin you need to run `ionic run browser` (make sure you have browser platform installed as well).

**Comment by gopi2mohan** [comment] 2017-01-23 13:24
same problem for me also i am able to build my apk file without any errors but when i try to run it on browser 'ionic serve' i am getting the same error @HamzaLJ  how did you solve this issue

**Comment by roshandhabekar** [comment] 2017-03-23 13:08
guy's can any one help me , whenever i enter the push initializing code to my iniatialize app block 
, my app got stucked and it stopped working with "UNFORTUNATELY STOPPED WORKING" while running on android device`



`this.platform.ready().then(() => {
      StatusBar.styleDefault();
      let push = Push.init({
        android: {
          senderID: "#########"
        },
        ios: {
          alert: "true",
          badge: false,
          sound: "true"
        },
        windows: {}
      });
      push.on('registration', (data) => {
        if (data) {
          console.log("device token ->", data.registrationId);
        } else {
          console.log('No data returned.');
        }
        //TODO - send device token to server
      });`

**Comment by ihadeed** [comment] 2017-05-17 12:05
This is fixed in latest 3.x

**Closed** 2017-05-17 12:05 UTC

**Comment by vahidvdn** [comment] 2017-06-18 14:01
I'm using ionic1.x and get the same error. What I do is:

```
$ionicPush.register().then(function(t) {
    alert(JSON.stringify(t));
    $scope.token = t.token;
    opt = {ignore_user: true};
    return $ionicPush.saveToken(t, opt);
}).then(function(t) {
    alert('Token saved:', t.token);
});

$rootScope.$on('cloud:push:notification', function(event, data) {
    var msg = data.message;
    alert(msg.title + ': ' + msg.text);
});

// HERE I GET ERROR: $ionicPush.on is not a function.
$ionicPush.on('notification', function(data) {
    // do something with the push data
    // then call finish to let the OS know we are done
    $ionicPush.finish(function() {
        alert("processing of push data is finished");
        }, function() {
            alert("something went wrong with push.finish for ID = " + data.additionalData.notId)
    }, data.additionalData.notId);
});
```

I get push notification permission from my device and also the token is generated fine, but cannot receive any notifications. (Test with and without `$ionicPush.on`)

Any idea?

**Comment by ihadeed** [comment] 2017-06-18 21:23
@vahidvdn this issue has nothing to do with Ionic Cloud
