### ISSUE TITLE
Plugin 3DTouch bug

### ISSUE THREAD

**Issue by Bouzmine** [driftyco/ionic-native#232] opened 2016-06-17 23:32 UTC
Hi,

I am having trouble with the 3DTouch plugin which was recently added. The `configureQuickActions` is OK, it's the `onHomeIconPressed()` that's bugging.

> TypeError: undefined is not an object (evaluating 'util_1.get(window, pluginObj.pluginRef)[methodName].apply')

I think this could be related with #106.

**Comment by ihadeed** [comment] 2016-06-18 03:00
Hey @Bouzmine 

Thanks for reporting this issue.

The problem is with the wrapper I created for that method. It's actually not a method, it's a property. (See https://github.com/EddyVerbruggen/cordova-plugin-3dtouch#onhomeiconpressed)

Since you are using the plugin, can you tell me which of the following is a better option:
1. Wrap the property, then use it as intended by the original developer, so your markup would look something like this:
```typescript
import {ThreeDeeTouch} from 'ionic-native';

...

ThreeDeeTouch.onHomeIconPressed = (payload: any) => {
// do something with payload.type
// do something with payload.title
};
```

2. Write a custom wrapper so we can still provide an observable. The usage would be like this:
```typescript
// import plugin
...
let subscription = ThreeDeeTouch.onHomeIconPressed().subscribe(
  (payload: any) => {
    // do stuff with data
  }
);
...
// then eventually stop processing that data
subscription.unsubscribe();
```

I'm not so sure if wrapping it with an observable would really work, but it should :grin:

..

Let me know what you think is a better option, as I personally haven't used this plugin.

**Comment by Bouzmine** [comment] 2016-06-18 13:52
I think option number 2 would better fit with Ionic Native's objective (providing observable wrapper for Cordova plugin, if I recall correctly). That said, if option 2 cannot work, option 1 would be just fine.

**Comment by mlynch** [comment] 2016-06-21 03:40
@ihadeed what about a 3rd option, something like:

```ts
    /**
     * When a home icon is pressed, your app launches and this JS callback is invoked.
     * @returns {Observable<any>} returns an observable that notifies you when he user presses on the home screen icon
     */
    static onHomeIconPressed(): Observable<any> {
      return new Observable(observer => {
        window.ThreeDeeTouch && window.ThreeDeeTouch.onHomeIconPressed = observer.next.bind(payload);
      })
    }
```

**Comment by ihadeed** [comment] 2016-06-21 10:03
@mlynch Yes that's exactly what I meant.

**Comment by ihadeed** [comment] 2016-06-26 15:16
This should be fixed in next release. Let me know if you still have problems with it.

**Closed** 2016-06-26 15:15 UTC
Labels: bug, plugin:3dtouch
