### ISSUE TITLE
TODO: $cordovaFileOpener2

### ISSUE THREAD

**Issue by andredas** [driftyco/ionic-native#416] opened 2016-08-10 12:04 UTC
It would be great to have a wrapper for this plugin.

[https://github.com/pwlin/cordova-plugin-file-opener2](https://github.com/pwlin/cordova-plugin-file-opener2)

**Comment by ihadeed** [comment] 2016-08-15 06:13
Duplicate of https://github.com/driftyco/ionic-native/issues/295

**Closed by ihadeed** 2016-08-15 06:13 UTC
Labels: feature request
