### ISSUE TITLE
 Radio buttons not being checked due to race condition in ionic threads when using mfp plugin login functionality.

### ISSUE THREAD

**Issue by sruthakeerthikotla** [driftyco/ionic-native#1595] opened 2017-05-22 04:08 UTC
When the MobileFirst Platforms plugin cordova-plugin-mfp 's WLAuthorizationManager.login() function is used, the radio buttons are not getting checked. (The sample app can be found in the issue mentioned here : http://stackoverflow.com/questions/43726154/unable-to-toggle-between-radio-button-after-authenticating-user-using-mfp-8-0 ). If a small timeout (as shown in the code below) is added to ionic's function, the radio buttons get checked properly. Here the conditions to add timeout are to ensure that only the view related threads are delayed slightly. I have identified these threads for the sample in the above link by debugging manually line after line and these conditions might not be applicable to any other applications.

```
function test2()
{
    setTimeout(function(){ 
    }, 1);  
}
/**
 * @param {?} view
 * @return {?}
 */
function checkAndUpdateView(view) {
    try{
    if( view.component.navCtrl._ids == 1 && view.component.navCtrl.id == "n4"
    )
    {
        test2();
    }            
    }catch(e){}
    Services.updateDirectives(view, 0 /* CheckAndUpdate */);
    execEmbeddedViewsAction(view, ViewAction.CheckAndUpdate);
    execQueriesAction(view, 33554432 /* TypeContentQuery */, 268435456 /* DynamicQuery */, 0 /* CheckAndUpdate */);
    callLifecycleHooksChildrenFirst(view, 1048576 /* AfterContentChecked */ |
        (view.state & 1 /* FirstCheck */ ? 524288 /* AfterContentInit */ : 0));
    Services.updateRenderer(view, 0 /* CheckAndUpdate */);
    execComponentViewsAction(view, ViewAction.CheckAndUpdate);
    execQueriesAction(view, 67108864 /* TypeViewQuery */, 268435456 /* DynamicQuery */, 0 /* CheckAndUpdate */);
    callLifecycleHooksChildrenFirst(view, 4194304 /* AfterViewChecked */ |
        (view.state & 1 /* FirstCheck */ ? 2097152 /* AfterViewInit */ : 0));
    if (view.def.flags & 2 /* OnPush */) {
        view.state &= ~2 /* ChecksEnabled */;
    }
    view.state &= ~1 /* FirstCheck */;
}
```

**Comment by ihadeed** [comment] 2017-05-22 06:27
Duplicate of #1547 ... not an Ionic Native issue..

**Closed by ihadeed** 2017-05-22 06:27 UTC
