### ISSUE TITLE
Native plugins not working in RC1

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic-native#718] opened 2016-10-17 22:39 UTC
I was having new problems with the BLE plugin in RC0, so I updated to RC1 as per the blog, and now it is totally broken. So I installed a new app:

```
ionic start --v2 VC3 sidemenu
cd VC3
ionic plugin add cordova-plugin-ble-central
```

Modified page1.ts to this:

```
import { Component } from '@angular/core';
import { BLE } from 'ionic-native';

import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-page1',
  templateUrl: 'page1.html'
})
export class Page1 {

	public bleresult:string;

  constructor(public navCtrl: NavController) {

  }

	testBLE() {
		BLE.isEnabled().then((result)=>{
			this.bleresult = JSON.stringify(result);
			console.log('BLE.isEnabled() -. ' + JSON.stringify(result));
		});
	}

}
```

Then built it and ran it on an iPad using XCode:

```
ionic build ios; cordova prepare
```

This gives the error below. The same applies to the Background plugin.
And yes, I tried removing and reinstalling ionic and cordova, no change:

```
sudo npm rm -g ionic cordova
sudo npm i -g ionic@latest cordova@latest
```

Now I'm totally stuck. My previously-working RC0 project is now broken, and I desperately need to deliver a bug fix to the client.

Any ideas????

```
ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X Sierra
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a 
```

```
[Warning] Native: tried calling t.isEnabled, but the t plugin is not installed. (console-via-logger.js, line 173)
[Warning] Install the t plugin: 'ionic plugin add cordova-plugin-ble-central' (console-via-logger.js, line 173)
[Error] EXCEPTION: Uncaught (in promise): plugin_not_installed
	handleError (main.js:5:24980)
	next (main.js:7:6295)
	(anonymous function) (main.js:6:30530)
	__tryOrUnsub (main.js:6:25446)
	next (main.js:6:24800)
	_next (main.js:6:24119)
	next (main.js:6:23791)
	next (main.js:6:28565)
	emit (main.js:6:30304)
	triggerError (main.js:7:2380)
	onHandleError (main.js:7:1970)
	runGuarded (polyfills.js:3:11039)
	r (polyfills.js:3:8117)
	i (polyfills.js:3:8166)
	invoke (polyfills.js:3:15184)
	dispatchEvent
	touchEnd (main.js:17:1377)
	(anonymous function)
[Error] ORIGINAL STACKTRACE:
	handleError (main.js:5:25114)
	next (main.js:7:6295)
	(anonymous function) (main.js:6:30530)
	__tryOrUnsub (main.js:6:25446)
	next (main.js:6:24800)
	_next (main.js:6:24119)
	next (main.js:6:23791)
	next (main.js:6:28565)
	emit (main.js:6:30304)
	triggerError (main.js:7:2380)
	onHandleError (main.js:7:1970)
	runGuarded (polyfills.js:3:11039)
	r (polyfills.js:3:8117)
	i (polyfills.js:3:8166)
	invoke (polyfills.js:3:15184)
	dispatchEvent
	touchEnd (main.js:17:1377)
	(anonymous function)
[Error] s@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:8555
s@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:8370
file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:8881
invokeTask@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:14034
onInvokeTask@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/main.js:7:1607
invokeTask@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:13977
runTask@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:11399
i@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:8013
invoke@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/polyfills.js:3:15183
dispatchEvent@[native code]
touchEnd@file:///var/containers/Bundle/Application/537A6AA3-446D-499E-A397-EA1E45494354/VC3.app/www/build/main.js:17:1376
[native code]
	handleError (main.js:5:25158)
	next (main.js:7:6295)
	(anonymous function) (main.js:6:30530)
	__tryOrUnsub (main.js:6:25446)
	next (main.js:6:24800)
	_next (main.js:6:24119)
	next (main.js:6:23791)
	next (main.js:6:28565)
	emit (main.js:6:30304)
	triggerError (main.js:7:2380)
	onHandleError (main.js:7:1970)
	runGuarded (polyfills.js:3:11039)
	r (polyfills.js:3:8117)
	i (polyfills.js:3:8166)
	invoke (polyfills.js:3:15184)
	dispatchEvent
	touchEnd (main.js:17:1377)
	(anonymous function)
[Error] Unhandled Promise rejection: (8)
"plugin_not_installed"
"; Zone:"
"angular"
"; Task:"
"Promise.then"
"; Value:"
"plugin_not_installed"
undefined
	(anonymous function) (console-via-logger.js:173)
	o (polyfills.js:3:7722)
	r (polyfills.js:3:8149)
	i (polyfills.js:3:8166)
	invoke (polyfills.js:3:15184)
	dispatchEvent
	touchEnd (main.js:17:1377)
	(anonymous function)
[Error] Error: Uncaught (in promise): plugin_not_installed — polyfills.js:2
	(anonymous function) (console-via-logger.js:173)
	o (polyfills.js:3:7900)
	r (polyfills.js:3:8149)
	i (polyfills.js:3:8166)
	invoke (polyfills.js:3:15184)
	dispatchEvent
	touchEnd (main.js:17:1377)
	(anonymous function)
```

**Comment by mlynch** [comment] 2016-10-18 00:03
Taking a look

**Comment by mlynch** [comment] 2016-10-18 00:21
Hmm, I just tested your example above and it works fine for me. My info:

```bash
max@ionitron:~/apps/VC3$ ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
Ionic App Scripts Version: 0.0.36
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a


--------------------------------
max@ionitron:~/apps/VC3$
```

Try doing this instead for the build:

```bash
$ npm run build
$ cordova prepare ios
```

Then open the xcode project and run that from xcode.

**Comment by thomaswb** [comment] 2016-10-18 00:32
Thanks for the rapid response, but I still get the same result, plugin not installed, both in the simulator and a device. Could it be that I am using later versions of these?

```
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X Sierra
Node Version: v6.7.0
```

**Comment by mlynch** [comment] 2016-10-18 00:44
Closing as a duplicate of #718 as this has nothing to do with Ionic Framework RC versions, but will continue to discussion here to see what's up

**Closed by mlynch** 2016-10-18 00:44 UTC

**Comment by thomaswb** [comment] 2016-10-18 00:57
Sorry, I don't get you. This is #718, so what is it a duplicate of?

I believe it is to do with RC versions. I had a beta 10 app that was working perfectly with BLE. I created a new RC0 app and moved all my app's code into that as per the RC0 release notes, without changing the way BLE was accessed (global ble) and that worked for a while. Then for no apparent reason, the global ble disappeared, so I tried to access it using the import { BLE } method in the docs, and that's when the trouble started...

**Comment by mlynch** [comment] 2016-10-18 01:02
Sorry I meant #602.

It's not an RC issue because Ionic Framework doesn't interact with this module. They are separate, though we did make a lot of changes all the same time for RC0 so people are grouping them together which we're trying to get out of people's heads :D

So, in your examples, how are you calling `testBLE()`? I called mine from a button handler in the template, but if you're calling it before platform ready then it's going to fail

**Comment by mlynch** [comment] 2016-10-18 01:02
Any chance you could zip up the whole directory from your failing side menu example and email it to me? max@ionic.io

**Comment by thomaswb** [comment] 2016-10-18 01:29
I had already read #602, tried all the remedies in it, they didn't fix the problem. Not sure why 602 was closed, there doesn't seem to be a clear fix.

I'm calling testBLE from a button, so no problem with platform ready.

I'll email you my project.

**Comment by mlynch** [comment] 2016-10-18 01:34
Thanks. The reason we closed that is we keep finding, in almost every instance, that something else is wrong. That doesn't make it not an issue, it just makes it invalid from a technical standpoint. I'm keeping a very open mind on this though.
