### ISSUE TITLE
Network onConnect / onDisconnect event don't fire

### ISSUE THREAD

**Issue by chsakell** [driftyco/ionic-native#572] opened 2016-09-23 19:49 UTC
[Network](http://ionicframework.com/docs/v2/native/network/) native plugin events seem to stop firing. [This](https://github.com/chsakell/ionic2-angular2-firebase/blob/master/app/app.ts#L57-L84) code used to work but not anymore.

Any suggestions?

Thanks

**Comment by mlynch** [comment] 2016-09-23 19:51
Thanks, duplicate of #551

**Closed by mlynch** 2016-09-23 19:51 UTC

**Comment by mlynch** [comment] 2016-09-24 21:51
Can you try the most recently release? I tested this and it worked fine on my end, couldn't repro

**Comment by chsakell** [comment] 2016-09-30 18:16
Works fine @mlynch . I had to migrate ionic 2 to RC.0 before trying it.

Thanks again.
