### ISSUE TITLE
Device and DeviceAccounts do not work

### ISSUE THREAD

**Issue by samarthagarwal** [driftyco/ionic-native#848] opened 2016-12-05 13:25 UTC
On Ionic 2, none of these are working. Please check.

**Comment by ihadeed** [comment] 2016-12-05 14:05
What doesn't work? Can you share any errors you're getting along with steps to reproduce?

**Comment by samarthagarwal** [comment] 2016-12-05 14:08
Need help with getting the Device UUID. 
I have used the following code `import {Device} from 'ionic-native';`
Then in my constructor, `console.log(Device.device.uuid);`
It gives `undefined`.
I also tried using `DeviceAccounts` and trying `console.log(DeviceAccounts.getEmail());` gives me `t {__zone_symbol__state: false, __zone_symbol__value: "cordova_not_available"}` even on the phone.
Update: I am now getting `t {__zone_symbol__state: null, __zone_symbol__value: []}`

**Comment by ihadeed** [comment] 2016-12-05 20:57
Are you wrapping your code with `this.platform.ready().then(() => { ... });` ?

**Comment by samarthagarwal** [comment] 2016-12-05 21:02
Yes of course. Tried with and without that.

**Comment by ihadeed** [comment] 2016-12-06 11:53
`DeviceAccounts` works fine.

All methods return a Promise, I just noticed your usage just console logs the returned value of the function instead of what the promise resolved.

I can confirm that Device plugin doesn't work, I will close this issue since we have an issue open for the Device plugin #851

**Closed by ihadeed** 2016-12-06 11:53 UTC
Labels: need to reproduce, needs reply
